In [1]:
import numpy as np
from scipy import linalg
import math

Define ket vectors (zero, one) and indentity I. 

In [2]:
zero = np.array([1, 0])
one = np.array([0, 1]) 
I = np.identity(2)

Define Pauli Matrices.

In [3]:
p_x = np.array([[0.,  1.], [1.,  0.]])
p_y = np.array([[0., -1j], [1j,  0.]])
p_z = np.array([[1.,  0.], [0., -1.]])

Define and check states for 2 qubit case. 

In [4]:
state00= np.kron(zero,zero)
state01= np.kron(zero,one)
state11= np.kron(one, one)
state10= np.kron(one, zero)

state00, state01, state11, state10

(array([1, 0, 0, 0]),
 array([0, 1, 0, 0]),
 array([0, 0, 0, 1]),
 array([0, 0, 1, 0]))

Define Quantum State Transfer Hamiltonian (Heisenberg Model) and check.

In [5]:
Hamiltonian = (np.kron(p_x,p_x) + np.kron(p_y,p_y) + np.kron(p_z,p_z) + np.kron(I,I))/2
Hamiltonian

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

Define unitary evolution and check if result is in expected form.

In [6]:
unitary = linalg.expm(Hamiltonian)

print(unitary)
unitary.shape

[[2.71828183+0.j 0.        +0.j 0.        +0.j 0.        +0.j]
 [0.        +0.j 1.54308063+0.j 1.17520119+0.j 0.        +0.j]
 [0.        +0.j 1.17520119+0.j 1.54308063+0.j 0.        +0.j]
 [0.        +0.j 0.        +0.j 0.        +0.j 2.71828183+0.j]]


(4, 4)

Define Time Evolution and check that at 0 we get identity.

In [7]:
def timeev(t):
    return linalg.expm(-1j*Hamiltonian*t)

timeev(0)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

Check initial time evolution for state01. 

In [8]:
initial = timeev(0)@state01
initial

array([0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j])

Check at intervals, upto π.

In [9]:
timeev(1)@state01

array([0.        +0.j        , 0.54030231+0.j        ,
       0.        -0.84147098j, 0.        +0.j        ])

In [10]:
timeev(1.57)@state01

array([0.        +0.j        , 0.00079633+0.j        ,
       0.        -0.99999968j, 0.        +0.j        ])

In [11]:
timeev(0.785)@state01

array([0.        +0.j        , 0.70738827+0.j        ,
       0.        -0.70682518j, 0.        +0.j        ])

In [12]:
timeev(0.392)@state01

array([0.        +0.j        , 0.92414683+0.j        ,
       0.        -0.38203747j, 0.        +0.j        ])

In [13]:
final = timeev(math.pi)@state01
final 

array([ 0.+0.00000000e+00j, -1.+0.00000000e+00j,  0.-2.35127499e-16j,
        0.+0.00000000e+00j])

Check fidelity.

In [14]:
fidelity = abs(np.dot(final,np.conjugate(initial)))**2
print(round(fidelity, 4))

1.0


As expected, state01 has transferred with full fidelity after one complete time evolution. 